---
version: "3"
services:
  kanji_genzouw_com_db:
    image: mysql:5.7.29
    volumes:
      - kanji_genzouw_com_db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: kanji_genzouw_com_db
      MYSQL_USER: kanji_genzouw_com_user
      MYSQL_PASSWORD: kanji_genzouw_com_pass
      MYSQL_ROOT_PASSWORD: rootroot
    restart: always
    ports:
      - 3309:3306

volumes:
  kanji_genzouw_com_db_data: {}

      #wordpress:
      #  depends_on:
      #    - db
      #  build:
      #    context: .
      #  ports:
      #    - "10104:80"
      #  restart: always
      #  volumes:
      #    - ./html:/var/www/html
      #  environment:
      #    WORDPRESS_DB_HOST: db:3306
      #    WORDPRESS_DB_USER: wordpress
      #    WORDPRESS_DB_PASSWORD: wordpress
      #    WORDPRESS_DB_NAME: wordpress
